# Funding configuration for this project
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [AdamDanielHarris]  # Replace with your GitHub username
