---
name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Test before release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git bash
          source functions
          EnsurePython3WithYaml

      - name: Run test suite
        run: |
          chmod +x tests/run_tests.sh
          ./tests/run_tests.sh

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ## Repository Management Tool ${{ github.ref_name }}
            
            Download and extract the archive, then run `./repos` to get started.
            
            See the README.md for full documentation.
          draft: false
          prerelease: false

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
